# Generated by Django 5.0.6 on 2024-06-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuname', models.CharField(max_length=30)),
                ('usn', models.IntegerField()),
                ('marks', models.IntegerField()),
            ],
        ),
    ]
